name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: check
        uses: tj-actions/changed-files@4563c729c555b4141fac99c80f699f571219b836
        with:
          files: |
            .github/workflows/code-quality.yml
            gradle/libs.versions.toml
            gradle/kotlin-js-store/**
            **/*.kt
            **/*.kts
  spotless:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: 'false' # needs.file-changes.outputs.any == 'true'
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'zulu'
          java-version: |
            11
            17

      - uses: gradle/actions/setup-gradle@76d3b998d4cef76a821dbcee71a9172ce986bb30
      - name: Cache Build files
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Check spotless/ktlint rules
        run: ./gradlew spotlessCheck

  api-check:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'zulu'
          java-version: |
            11
            17

      - uses: gradle/actions/setup-gradle@76d3b998d4cef76a821dbcee71a9172ce986bb30
      - name: Cache Build files
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Check public api compatibility
        run: ./gradlew checkLegacyAbi