name: Publish

on:
  push:
    tags: [ v* ]
    branches: [ main ]

env:
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: check
        uses: tj-actions/changed-files@3b04099b21072562f07469c10deb182b24236ca9
        with:
          files: |
            .github/workflows/publish.yml
            gradle/libs.versions.toml
            gradle/kotlin-js-store/**
            **/*.kt
            **/*.kts
  publish:
    name: Publish to Maven
    runs-on: macos-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-java@ead9eaa3cfe0b0fc2fa749519ae09c3d4f4080b0
        with:
          distribution: 'zulu'
          java-version: |
            11
            17

      - uses: gradle/actions/setup-gradle@76d3b998d4cef76a821dbcee71a9172ce986bb30
      - name: Cache Build files
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Publish
        run: ./gradlew clean publishAllPublicationsToMavenCentralRepository

  publish-docs:
    name: Publish KDoc to Github Pages
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-java@ead9eaa3cfe0b0fc2fa749519ae09c3d4f4080b0
        with:
          distribution: 'zulu'
          java-version: |
            11
            17

      - uses: gradle/actions/setup-gradle@76d3b998d4cef76a821dbcee71a9172ce986bb30

      - name: Cache Build files
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Build Docs
        run: ./gradlew clean dokkaGenerate

      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: docs
          folder: build/dokka/html
          single-commit: true