name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/actions/setup-gradle@76d3b998d4cef76a821dbcee71a9172ce986bb30

      - name: Cache Build files
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4
        with:
          path: |
            ~/.konan
            ~/.gradle
            %USERPROFILE%\.konan
            %USERPROFILE%\.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Test Windows Target
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: ./gradlew windowsTest

      - name: Test Apple Targets
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: ./gradlew macosX64Test

      - name: Test Linux Target
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: ./gradlew linuxX64Test

      - name: Test JVM Target
        run: ./gradlew jvmTest

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@e5453d864979a2b201453695ee1db0acac11b14b
        if: always()
        with:
          report_paths: 'build/test-results/**/TEST-*.xml'

      - name: Archive test reports
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/**/**
