name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/actions/setup-gradle@v4

      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
            ~/.gradle
            %USERPROFILE%\.konan
            %USERPROFILE%\.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Test Windows Target
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: ./gradlew windowsTest

      - name: Test Apple Targets
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: ./gradlew macosX64Test

      - name: Test Linux Target
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: ./gradlew linuxX64Test

      - name: Test JVM Target
        run: ./gradlew jvmTest

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'build/test-results/**/TEST-*.xml'

      - name: Archive test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/**/**
